### ISSUE TITLE
CSV Import Functionality

### ISSUE THREAD

**Issue by ojedatony1616** [DistrictDataLabs/logbook#2]
Click Choose File button, prompt user to choose directory and file name, import CSV file containing email, name, action, detail, date, and IP address into a log table.

**Comment by bbengfort** [comment]
This is a great feature; just a question of when to add it. The implementation will be via a Django management command for now.

**Comment by bbengfort** [comment]
The Django management command has been implemented; now we need to deal with the upload CSV to the website functionality since uploading data to heroku is hard.
