### ISSUE TITLE
Are there any other data sources?

### ISSUE THREAD

**Issue by bbengfort** [DistrictDataLabs/logbook#8]
What other data can we add to events and actions?

**Comment by ojedatony1616** [comment]
There's a bunch of data about what emails people open and what links they click on in Mailchimp that can serve to paint a picture of what topics they are interested in. 

It would be great to get website data in here also - what links people click on, page flow, info about the amount of time they spend on pages, etc. Not sure if there's a way to tie that back to an email or if Google Analytics even lets you download info by session (based on the little bit of research I've done, don't think so).
